# Generated by Django 3.2.6 on 2022-01-19 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_album_track'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('album', 'order')},
        ),
    ]
