# Generated by Django 3.2.6 on 2022-01-19 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_track_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Categories',
            fields=[
                ('categories_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('categories_name', models.CharField(max_length=200)),
                ('image_class_name', models.CharField(blank=True, max_length=200, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_model', models.CharField(blank=True, max_length=200, null=True)),
                ('product_group', models.CharField(blank=True, max_length=200, null=True)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22, null=True)),
                ('product_old_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22, null=True)),
                ('app_user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('app_data_time', models.DateTimeField(auto_now_add=True)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='product_category', to='blog.product_categories')),
            ],
        ),
    ]
