# Generated by Django 3.2.6 on 2022-01-23 09:33

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_document'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='document',
            managers=[
                ('objects1', django.db.models.manager.Manager()),
            ],
        ),
    ]
