# Generated by Django 3.2.6 on 2022-01-23 09:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_document_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=10)),
            ],
            managers=[
                ('objects1', django.db.models.manager.Manager()),
            ],
        ),
    ]
